djangopassword/djangopassword/urls.py
from django.contrib import admin
from django.urls import path,include
from passApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('password/', include('passApp.urls')),
    path('', views.index, name = 'index'),
    path('logout/', views.user_logout , name = 'logout'),
    path('special/', views.special , name = 'special'),

]

djangopassword/passApp/firstproject/urls.py
from django.contrib import admin
from django.urls import path
from palamuAppEka import views


urlpatterns = [
    path('',views.index, name ='index'),
    path('admin/', admin.site.urls),
]

djangopassword/passApp/urls.py
from django.urls import path
from passApp import views

app_name = 'passApp'

urlpatterns = [
path('register/', views.register, name = 'register'),
path('login/', views.user_login, name = 'user_login')

]

djangopassword/passApp/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.PROTECT)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)
    def __str__(self):
        return self.user.username

djangopassword/passApp/forms.py
from django import forms
from django.contrib.auth.models import User
from passApp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

djangopassword/passApp/views.py
from django.shortcuts import render
from passApp.forms import UserForm,UserProfileInfoForm

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,login, logout


# Create your views here.
def index(request):
    return render(request,'passApp/index.html',{'hello':'hello'})


@login_required
def special(request):
    return HttpResponse('You are Logged in')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered =  False
    if request.method == 'POST':
        User_form = UserForm(data = request.POST)
        UserProfileInfo_form = UserProfileInfoForm(data = request.POST)

        if User_form.is_valid() and UserProfileInfo_form.is_valid():
            user = User_form.save()
            user.set_password(user.password)
            user.save()
            profile = UserProfileInfo_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic =request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(User_form.errors,UserProfileInfo_form.errors)
    else:
        User_form = UserForm()
        UserProfileInfo_form = UserProfileInfoForm()


    return render(request,'passApp/registrations.html',{'registered': registered, 'User_form': User_form, 'UserProfileInfo_form': UserProfileInfo_form})




def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username,password = password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('some one tried to login to {} with {}'.format(username,password))
            return HttpResponse('login detals wrong')
    else:
        return render(request,'passApp/login.html',{})

djangopassword/templates/passApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
<div class="container">
  <ul class="nav navbar-nav">
    <li ><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
    <li><a class="navbar-link" href="{% url 'passApp:register' %}">Register</a></li>
    {% if user.is_authenticated %}
      <li><a class="navbar-link" href="{% url 'logout' %}">LogOut</a></li>
    {% else %}

      <li><a class="navbar-link" href="{% url 'passApp:user_login' %}">LogIn</a></li>

  {% endif %}


   </ul>
 </div>
</nav>
<div class="container">
  {%block body_block %}
  {% endblock %}
</div>

  </body>
</html>

djangopassword/templates/passApp/index.html
{% extends 'passApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
 <h1>Django Level 5</h1>
</div>
{{ 'hello' }}

{% endblock %}

djangopassword/templates/passApp/login.html
{% extends 'passApp/base.html' %}
{% block body_block %}

<div class="jumbotron">

  <form  action="{% url 'passApp:user_login'  %}" method="post">
     {% csrf_token %}
   <label for="username">Username: </label>
   <input type="text" name="username" placeholder="Enter your Username">
   <label for="password"> Password: </label>
   <input type="text" name="password" placeholder="Enter your Password">
   <input type="submit" name="" value="LogIn">

  </form>

</div>








{% endblock %}

djangopassword/templates/passApp/registrations.html
{% extends 'passApp/base.html' %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h2>Thank You For Registering.</h2>
  {% else %}
     <h2>Register Here!</h2>
     <h3>Fillout the form:</h3>
     <form  method="post" enctype="multipart/form-data">
       {% csrf_token %}
        {{ User_form.as_p }}
        {{ UserProfileInfo_form.as_p }}
        <input type="submit" name="" value="register">
     </form>

  {% endif %}

</div>
{% endblock %}